drop table products;
CREATE TABLE PRODUCTS (
    id int generated by default as identity (start with 1) primary key,
    name varchar(32) not null,
    category varchar(32) not null,
    amount int not null,
    primary key (id)
);

insert into PRODUCTS values (1, 'Ryż', 'CARBS', 5);

