drop table products;
CREATE TABLE PRODUCTS (
    id int generated by default as identity (start with 1) primary key,
    name varchar(32) not null,
    category varchar(32) not null,
    amount int not null,
    unit varchar(32) not null,
    primary key (id)
);

insert into PRODUCTS values (1, 'Ryż', 'WW', 100, 'GRAM');

----

drop table users;
CREATE TABLE USERS (
    user_id int generated by default as identity (start with 1) primary key,
    user_name varchar(32) not null,
    user_password varchar(32) not null,
    created_at timestamp not null,
    active int not null,
    primary key (user_id)
);

insert into USERS values (0, 'mj', 'admin123', '2024-03-22 19.41.59', 1);
